
# ==========================================================
# FITPASS - APPLICATION
# ==========================================================

spring.application.name=fitpass


# ==========================================================
# SERVER
# ==========================================================

server.port=8081


# ==========================================================
# DATABASE - POSTGRESQL
# ==========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/fitpass
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================================
# JPA / HIBERNATE
# ==========================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# ==========================================================
# DATABASE INITIALIZATION
# ==========================================================

spring.sql.init.mode=never